# Generated by Django 5.2.1 on 2025-05-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cca2', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
